from drf_spectacular.utils import OpenApiExample, OpenApiResponse, extend_schema

from cart.serializers import CartSerializer
from docs.api.cart.config import NOT_FOUND_SCHEMA, TAGS

partial_update_schema = extend_schema(
    summary="Partially update a cart",
    description=(
        "Cart fields are generated by the service and cannot be changed directly. "
        "This endpoint returns the cart's current state."
    ),
    tags=TAGS,
    responses={
        200: CartSerializer,
        404: OpenApiResponse(
            response=NOT_FOUND_SCHEMA,
            description="No cart matches the supplied ID.",
            examples=[
                OpenApiExample(
                    "Cart not found",
                    summary="Cart not found",
                    value={"detail": "No Cart matches the given query."},
                    response_only=True,
                )
            ],
        ),
    },
)
