from drf_spectacular.utils import OpenApiExample, OpenApiResponse, extend_schema

from cart.serializers import CartSerializer
from docs.api.cart.config import CART_EXAMPLE, NOT_FOUND_SCHEMA, TAGS

update_schema = extend_schema(
    summary="Update a cart",
    description=(
        "Cart fields are generated by the service and cannot be changed directly. "
        "This endpoint returns the cart's current state."
    ),
    tags=TAGS,
    responses={
        200: OpenApiResponse(
            response=CartSerializer,
            description="The cart's current state was returned.",
            examples=[
                OpenApiExample(
                    "Cart updated",
                    summary="Current cart state",
                    value=CART_EXAMPLE,
                    response_only=True,
                )
            ],
        ),
        404: OpenApiResponse(
            response=NOT_FOUND_SCHEMA,
            description="No cart matches the supplied ID.",
            examples=[
                OpenApiExample(
                    "Cart not found",
                    summary="Cart not found",
                    value={"detail": "No Cart matches the given query."},
                    response_only=True,
                )
            ],
        ),
    },
)
