# Generated by Django 6.0.7 on 2026-08-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='one_product_per_cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
