# Generated by Django 6.0.7 on 2026-08-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
